{% set name = "aws-error-utils" %}
{% set version = "2.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07107af2a2c26706cd9525b7ffbed43f2d07b50d27e39f9e9156c11b2e993c97

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - botocore
    - python >={{ python_min }}

test:
  imports:
    - aws_error_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/benkehoe/aws-error-utils
  summary: Error-handling functions for boto3/botocore
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
